### ISSUE TITLE
Agenda for the Resources meeting in Copenhagen

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/Resources#2]
Meeting dates: 30 May 2017
Time: 11:00-17:00

## Draft agenda

| Time |    Subject    |  Responsibility |
|:----------|:-------------|:--------|
|11:00-11:15 | Introduction |HMMG Convenors  |
| |Welcome and introduction |HMMG Convenors |
| |Roll call | All |
| | | |
|11:15-12:30 |Resource management and technology |HMMG Convenors |
||Resolution 857 - Official web access for ISO/TC 211 resources to support implementation of standards| HMMG Convenors|
|| Resolution 858 - ISO/TC 211 URI structure | HMMG Convenors |
|| Resolution 859  - ISO/TC 211 Maintenance groups structure | All |
||Recommendations to the plenary | HMMG Convenors| 
||Any other business | HMMG Convenors |
||||||
|12:30-13:30| Lunch | |
| 13:30-14:15 |TMG | TMG convenor |
| 14:15-15:00 | XMG | XMG convenor |
| 15:00-15:30 | Coffee break |
| 15:30-16:15 | GOM  | GOM Convenor |
| 16:15-17:00 | HMMG | HMMG Convenors |
| 17:00 | Meeting closure | |

**Comment by BrodeurJS** [comment]
**GOM draft Agenda**

Time | Subject | Responsibility
-- | -- | --
15:30 | 1.        Welcome | Convenor
  | 2.        Roll call of members | Members
  | 3.        Approval of agenda | Members
  | 4.        Programme of work | Convenor, members
  | 5.        def.isotc211.org repository | Convenor, members
  | 6.        Other | Convenor, Members
  | 7.        Report to the plenary | Convenor
16:15 | 8.        Close |
