### ISSUE TITLE
Resolution 858: ISO/TC 211 URI structure

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/Resources#4]
> “ISO/TC 211 resolves that all identifiable conformance classes, conformance tests, requirements and recommendations in ISO geographic information standards shall be identified by URIs with a given structure. ISO/TC 211 instructs the convenors of TMG, XMG, GOM, PMG and HMMG to develop the structure of the URIs and web resources in a draft report lead by Mr. Knut Jetlund. The report will be sent to the ISO/TC 211 secretariat for distribution to its members one month before the next plenary meeting. Once accepted, this report will be an input to the revision of 19105.”

Link to previous discussion (team members only): https://github.com/orgs/ISO-TC211/teams/resources/discussions/3

**Comment by jetgeo** [comment]
A suggested top level structure:
- The geodetic registry: https://registry.isotc211.org (suggested from the provider)
- Ontologies: https://def.isotc211.org (as described in ISO 19150)
- XML Schemas and example files: https://schema.isotc211.org  (To be discussed)

I bellieve the structure bellow def.isotc211.org and schemas.isotc211.org should be identical, if possible.
Suggestion: https://[def/schema].isotc211.org/191[??]/[Part]/[YYYY]/[namespace]/
e.g. https://schema.isotc211.org/19115/3/2016/...

- Requirements: https://standards.isotc211.org/191[??]/[Part]/[YYYY]/req/[reqName], e.g http://standards.isotc211.org/19115/3/2016/req/...
- Conformance classes: https://standards.isotc211.org/191[??]/[Part]/[YYYY]/conf/[confName], e.g http://standards.isotc211.org/19115/3/2016/conf/...
- Profiles:  https://standards.isotc211.org/191[??]/[Part]/[YYYY]/profiles/[profileName], e.g http://standards.isotc211.org/19160/1/2015/profiles/...

**Comment by PeterParslow** [comment]
See discussion at https://github.com/orgs/ISO-TC211/teams/resources

**Comment by tedhabermann** [comment]
We do not want to confuse the concepts of _publication year_ and _version_. This structure should be driven by versions and not publication years. See https://stackoverflow.com/questions/65718/what-do-the-numbers-in-a-version-typically-represent-i-e-v1-9-0-1

**Comment by cportele** [comment]
> The geodetic registry: https://registry.isotc211.org (suggested from the provider)

Are we sure that the geodetic register will be the only register managed in a TC 211 registry? Otherwise the URI probably should include "geodetic" somewhere?

**Comment by tedhabermann** [comment]
We did not discuss this suggestion and it did not make it into the report... I think it could avoid problems in the future. Perhaps this URL should be https://registry.isotc211.org/geodetic

**Comment by tedhabermann** [comment]
In the plenary Olaf suggested using https in the URI pattern.

**Comment by cportele** [comment]
I think using https is fine as long as we can be certain that all clients/agents de-referencing the URIs support https.

Already existing resources would continue to use the http URI?

This topic was also discussed in the W3C/OGC SDWWG, see for example https://lists.w3.org/Archives/Public/public-sdw-wg/2016Apr/0080.html that has some information on the W3C approach (see also https://www.w3.org/blog/2016/01/w3-org-supporting-https-and-hsts/).

**Comment by jetgeo** [comment]
I'll add both the registry question and the http/https issue to the report
