### ISSUE TITLE
Resolution 859: ISO/TC 211 Maintenance groups structure

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/Resources#5]
> “Considering the challenge of managing implementation resources ISO/TC 211 instructs the convenors of the TMG, XMG, GOM, PMG and HMMG, lead by Mr. Knut Jetlund, to discuss the current structure of the groups and, if a change is preferable, propose a way forward. The agreed proposal shall be presented at the next plenary meeting.”

Link to previous discussion (team members only): https://github.com/orgs/ISO-TC211/teams/resources/discussions/4

**Comment by jetgeo** [comment]
To get this discussuion started:
My believe is that the groups as they are now are working well. But we are missing an overall responsibillity for managing all resources for implementation.
I would suggest that this responsibillity is given to the HMMG, as the HM is fundamental for all work on implementations. Except for this, I believe the groups can be kept as they are.
But: I believe we should define more clearly the responsibility of each group. Right now, it can probably be found in resolutions, but it should be stated in a more structured manner.

The figure bellow is a first draft of how the resources for implementation are managed. Sorry about the ugly colours, no time for advanced layout...
![resourcesmanagement](https://user-images.githubusercontent.com/7501876/38664390-ba8cce38-3e39-11e8-80a5-f6b59787be05.png)

**Comment by BrodeurJS** [comment]
I am not sur who has the responsibility to derive resources HMMG or XMG and GOM? In the GOM ToR, it is GOM that has the responsilility to derive ontologies.
Suggest that we move the discussion by setting up the overarching Resource Group and define ToR for this group. Suggest to move HMMG, XMG, GOM, and XMG as official ISO/TC 211 subgroups of the RG. I think one of the responsibility of the RG would be the coordination of the overall activities done by the subgroups. the standardization of the resource structure and access, etc. The membership of this group need to be define. I think the ToR should just confirm the meeting stucture we are followingfor few years now. A figure like the one proposed by Knut should be integrated in the ToR (as an Annex) which explain the role of each group and the relationships between them.

**Comment by tedhabermann** [comment]
I'm not sure why a multi-layered structure is necessary here. Combining HMMG, XMG, GOM into one Resource Management Group (I'm not so worried about the TMG) is a simple solution that recognizes that we are working on the same thing - standards development driven by the HM. This combined structure also allows us to add resource types (say JSON) by adding a person(s) to this group rather than creating a new group.

**Comment by tedhabermann** [comment]
We need to work on automating the creation of these resources from the HM.

**Comment by tedhabermann** [comment]
We should not forget the work done several years ago on creating documents directly from the HM. This is another capability that could be very helpful.
